In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [4]:
# y was created as a result of an operation, so it has a grad_fn.

In [5]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [8]:
# .requires_grad_(...) changes an existing Tensor's requires_grad flag in-place. The input flag defaults to False if not given.

In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
# gradent

In [11]:
out.backward()

In [13]:
# print gradients d(out)/dx

In [14]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
# take a look at an example of jacobian-vector product:

In [25]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)
print(y.data.norm())

tensor([ 715.6339, -666.9367, -726.8312], grad_fn=<MulBackward>)
tensor(1218.6960)


In [26]:
# full jacobian-vector product

In [28]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([ 51.2000, 512.0000,   0.0512])


In [29]:
# stop autograd from tracking history on tensors

In [30]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
