In [1]:
# Tensors

In [14]:
from __future__ import print_function
import torch

In [15]:
# make uninitialized matrix

In [20]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.5573e+29,  7.3288e-43, -1.9019e+31],
        [ 7.3288e-43, -1.5479e+29,  7.3288e-43],
        [-1.8955e+31,  7.3288e-43, -1.7178e+29],
        [ 7.3288e-43, -3.3919e+32,  7.3288e-43],
        [-1.5479e+29,  7.3288e-43, -1.8988e+31]])


In [21]:
# consturct a randomly initialized matrix:

In [22]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9028, 0.2271, 0.0489],
        [0.3838, 0.3617, 0.1150],
        [0.8812, 0.1677, 0.8887],
        [0.0481, 0.0399, 0.7670],
        [0.6987, 0.4885, 0.4407]])


In [23]:
# construct a matrix filled zeros and of dtype long:

In [24]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [25]:
# construct a tensor directly from data:

In [26]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [27]:
# or create a tensor based on an existing tensor.These will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [30]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x) # override dtype, result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4941, -0.0026, -1.0376],
        [ 1.6130, -1.5480,  1.4564],
        [-1.5311,  2.1155, -0.4855],
        [-0.4720, -0.2112, -0.6433],
        [-0.5084, -0.7477, -0.3773]])


In [31]:
# get its size:

In [32]:
print(x.size())
# torch.size is in fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


In [33]:
# addition

In [34]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4851,  0.3329, -0.2265],
        [ 2.2482, -1.2570,  1.9317],
        [-0.5730,  2.4098, -0.2606],
        [ 0.0350, -0.0323, -0.1089],
        [-0.0068, -0.4379, -0.2299]])


In [35]:
print(torch.add(x, y))

tensor([[ 0.4851,  0.3329, -0.2265],
        [ 2.2482, -1.2570,  1.9317],
        [-0.5730,  2.4098, -0.2606],
        [ 0.0350, -0.0323, -0.1089],
        [-0.0068, -0.4379, -0.2299]])


In [37]:
result = torch.empty(5, 3) # providing an output tensor as argument
torch.add(x, y, out = result)
print(result)

tensor([[ 0.4851,  0.3329, -0.2265],
        [ 2.2482, -1.2570,  1.9317],
        [-0.5730,  2.4098, -0.2606],
        [ 0.0350, -0.0323, -0.1089],
        [-0.0068, -0.4379, -0.2299]])


In [38]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4851,  0.3329, -0.2265],
        [ 2.2482, -1.2570,  1.9317],
        [-0.5730,  2.4098, -0.2606],
        [ 0.0350, -0.0323, -0.1089],
        [-0.0068, -0.4379, -0.2299]])


In [39]:
# you can use standard numpy-like indexing with all bells and whistles!

In [40]:
print(x[:, 1])

tensor([-0.0026, -1.5480,  2.1155, -0.2112, -0.7477])


In [41]:
# resizing : if you want to resize/reshape tensor, you can use torch.view:

In [45]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [46]:
# if you have a one element tensor, uses .item() to get the value as a python number

In [48]:
x = torch.randn(1)
print(x)
print(x.item()+1)

tensor([-0.0130])
0.9870008509606123


In [49]:
# converting a torch tensor to a numpy array

In [50]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [51]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [52]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [53]:
# converting numpy array to torch tensor

In [54]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [55]:
# tensors can be moved onto any device using the .to method.

In [56]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.9870], device='cuda:0')
tensor([0.9870], dtype=torch.float64)
